name: Publish ui-components to NPM Registry

on:
  push:
    branches:
      - master
    paths:
      - "packages/ui-components/**"
jobs:
  publish:
    if: ${{ github.repository_owner == 'cockroachdb'}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: yarn install --production
        working-directory: ./packages/ui-components
      - name: Configure Git User
        run: |
          git config user.name "Github Actions"
          git config user.email "<actions@github.com>"
      - name: Bump version (prerelease)
        run: |
          yarn version --prerelease --preid="alpha"
          git push --all
        working-directory: ./packages/ui-components
      - name: Publish ui-components
        run: yarn publish --access public --tag next
        working-directory: ./packages/ui-components
        env:
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
